apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  namespace: demomaintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
        - name: maintenance:0.0.7
          image: 172.16.189.130:8082/edu.mv/maintenance
          ports:
            - containerPort: 8080
      restartPolicy: Always