apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  namespace: demomaintenance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
        - name: maintenance
          image: 172.16.189.130:8082/maintenance:0.0.6
          stdin: true
          tty: true
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred2