apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
        - name: maintenance
          image: maintenance:0.0.5
          ports:
            - containerPort: 8080