apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxNzIuMTYuMTg5LjEyODo4MDgyIjp7InVzZXJuYW1lIjoiZGVwbG95LXVzZXIiLCJwYXNzd29yZCI6IlBhc3MxMjMhIiwiZW1haWwiOiJkZUBkZXBsb3kuY29tIiwiYXV0aCI6IlpHVndiRzk1TFhWelpYSTZVR0Z6Y3pFeU15RT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2024-08-05T21:12:19Z"
  name: regcred
  namespace: default
  resourceVersion: "14582"
  uid: 99808891-e529-4700-be38-e936c2146362
type: kubernetes.io/dockerconfigjson
